### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by simplemademath** [nitely/python-react-v8#4]
Ok know i'm getting the following error:

Collecting python-react-v8
  Using cached python-react-v8-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    _configtest.c:1:1: error: thread-local storage is not supported for the current target
    __thread int some_threadlocal_variable_42;
    ^
    1 error generated.
    ld: warning: ignoring file /opt/local/lib/libffi.dylib, file was built for x86_64 which is not the architecture being linked (i386): /opt/local/lib/libffi.dylib
    
    Installed /private/var/folders/18/qhlp60bs4_x1lv3gq3dbxj280000gn/T/easy_install-gv7zmwna/v8-cffi-0.0.1/.eggs/cffi-1.5.2-py3.5-macosx-10.6-intel.egg
    Note: will not use '__thread' in the C code
    The above error message can be safely ignored
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    ld: unknown option: --start-group
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/unixccompiler.py", line 194, in link
        self.spawn(linker + ld_args)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command '/usr/bin/clang++' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 160, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 146, in call_command
        self.run_command(cmdname)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 10, in run
        self.build()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/cffi/setuptools_ext.py", line 109, in run
        base_class.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 447, in build_extensions
        self._build_extensions_serial()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_extensions_serial
        self.build_extension(ext)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/build_ext.py", line 557, in build_extension
        target_lang=language)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/ccompiler.py", line 717, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/unixccompiler.py", line 196, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command '/usr/bin/clang++' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/var/folders/18/qhlp60bs4_x1lv3gq3dbxj280000gn/T/easy_install-gv7zmwna/v8-cffi-0.0.1/setup.py", line 43, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command '/usr/bin/clang++' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
        run_setup(setup_script, args)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 240, in run_setup
        raise
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 164, in save_modules
        saved_exc.resume()
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/compat.py", line 65, in reraise
        raise value.with_traceback(tb)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 237, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/var/folders/18/qhlp60bs4_x1lv3gq3dbxj280000gn/T/easy_install-gv7zmwna/v8-cffi-0.0.1/setup.py", line 43, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command '/usr/bin/clang++' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/18/qhlp60bs4_x1lv3gq3dbxj280000gn/T/pip-build-0o48959j/python-react-v8/setup.py", line 40, in <module>
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content'])
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/drewbutcher/Documents/beesmath/venv/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1058, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command '/usr/bin/clang++' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/18/qhlp60bs4_x1lv3gq3dbxj280000gn/T/pip-build-0o48959j/python-react-v8/

Thank you for all the help!

Best,
Drew

**Comment by nitely** [comment]
[v8-cffi](https://github.com/nitely/v8-cffi#compatibility) does not distribute OSx compatible binaries and it supports Linux x64, only.

I'll try to compile the binaries for OSx later this week and ping you back so you can try it.

**Comment by simplemademath** [comment]
thank you :)  

I’m here if you need anything... this is going to solve a server side form validation issue that we were working on.

Our other option is to look into python-react 

Best,
Drew

**Comment by nitely** [comment]
I was able to make some progress on this. I compiled V8 and v8-cffi on OS X 10.11, everything seems to work well (after some changes to the code).

The only problem... the V8 static files (.a archives) are about ~640MB (!!), I've read in the v8-users mailing list this is the expected size, may be there are ways to bring it down but my knowledge about OS X is very limited. However, the final v8-cffi lib size (after linking those 600MB of archives) is 27MB.

So, I can't add those files to the repo, but I may be able to upload them to my dropbox. I'll also add some bash script to build v8 in OS X.

The V8 repo size is about ~500MB so the time/bandwidth wasted should be the same, probably worst since compiling V8 takes a long time.

**Comment by simplemademath** [comment]
Thank you Esteban!

We ended up using the python-react… it runs another sever but I didn’t find it so bad because the error on that server are related just to server side rendering where as the errors from our gulp files are related to the front end.  

Best,
Drew

**Comment by nitely** [comment]
Great! thanks for letting me know.

> We ended up using the python-react… it runs another sever

Yeah, my main gripe about python-react is the extra server and the server-server communication overhead. But it should have some upsides like the debugging support.
